Repository rust-lang/rustc-dev-guide, pull requests merged in 2020-10, with the labels that each got.

#907 Add a paragraph about reviewers and review latency in Getting Started chapter
  src/getting-started.md
Labels: waiting-on-review

#905 Document the usage of cargo-llvm-lines and -Ztimings.
  src/profiling.md
Labels: waiting-on-review

#883 add suggested workflow to setup nightly rustup for rust/
  src/building/suggested.md
Labels: waiting-on-review

#857 Explain stages in terms of the compiler currently running (take N+1)
  src/building/bootstrapping.md
Labels: Hard, help wanted, waiting-on-review

#910 Allow anyone to change the status of a PR
  triagebot.toml
Labels: waiting-on-review

#912 Document `Assemble` in bootstrap
  src/building/bootstrapping.md
Labels: waiting-on-review

#917 Recommend debug-logging instead of debug
  src/building/how-to-build-and-run.md
Labels: waiting-on-review

#915 Talk about git submodules
  src/git.md
Labels: waiting-on-review

#923 Explain pattern exhaustiveness checking
  src/pat-exhaustive-checking.md
Labels: waiting-on-review

#928 Add reference PRs for `r?` and `r+` comments
  src/getting-started.md
Labels: waiting-on-author

#930 Add a `check-in.sh` script to automate writing markdown links for weekly check-in
  ci/check-in.sh
Labels: waiting-on-review

#934 Improve prerequisites section for Windows
  src/building/prerequisites.md
Labels: waiting-on-review

#939 Fix broken tags in glossary
  src/appendix/glossary.md
Labels: waiting-on-review
