Repository rust-lang/rustc-dev-guide, pull requests merged in 2022-09, with the labels that each got.

#1450 Update for removal of RLS
  src/building/bootstrapping.md
  src/building/new-target.md
  src/contributing.md
  src/diagnostics.md
  src/git.md
  src/name-resolution.md
  src/overview.md
  src/rustc-driver.md
  src/tests/intro.md
Labels: waiting-on-review

#1453 Add reference for updating Windows PATH and fix typo
  src/building/prerequisites.md
Labels: waiting-on-review

#1446 Document multipart_suggestion derive on SessionSubdiagnostic
  src/diagnostics/diagnostic-structs.md
Labels: blocked

#1097 Explain the new valtree system for type level constants.
  src/const-eval.md
Labels: waiting-on-author

#1460 [Diagnostics] - Update docs to match renamed Diagnostics traits and macros
  src/diagnostics.md
  src/diagnostics/diagnostic-structs.md
  src/diagnostics/translation.md
Labels: blocked
