Repository rust-lang/rustc-dev-guide, pull requests merged in 2022-10, with the labels that each got.

#1456 Link to the correct page in "about this guide"
  src/about-this-guide.md
Labels: waiting-on-review

#1488 miri is no longer a submodule but a subtree.
  src/contributing.md
  src/git.md
Labels: waiting-on-author

#1487 Update rust-analyzer suggestions
  src/building/suggested.md
Labels: blocked

#1489 Update diagnostics to flat fluent message paths
  src/diagnostics/diagnostic-structs.md
  src/diagnostics/translation.md
Labels: waiting-on-review
