Repository rust-lang/rustc-dev-guide, pull requests merged in 2025-04, with the labels that each got.

#2313 Rustc pull
  rust-version
  src/notification-groups/about.md
  src/notification-groups/llvm.md
  src/tests/ci.md
  src/tests/ui.md
Labels: S-waiting-on-review, WG-rustc-dev-guide

#2320 Update table of contents in about-this-guide.md
  src/about-this-guide.md
Labels: S-waiting-on-review, WG-rustc-dev-guide

#2321 Document `-A {unused,internal_features}` ui test mode presets
  src/tests/ui.md
Labels: S-waiting-on-review, A-compiletest, A-test-suite, T-compiler, T-bootstrap

#2333 Coding conventions chapter cleaning
  src/conventions.md
Labels: S-waiting-on-author, WG-rustc-dev-guide

#2346 document `#[cfg(bootstrap)]` in dependencies
  src/SUMMARY.md
  src/building/bootstrapping/bootstrap-in-dependencies.md
Labels: S-waiting-on-author, T-bootstrap

#2266 Introduce a normalization chapter
  src/SUMMARY.md
  src/normalization.md
  src/solve/normalization.md
  src/solve/significant-changes.md
Labels: S-waiting-on-review, T-types

#2360 Add docs about stabilizing an edition
  src/guides/editions.md
Labels: S-waiting-on-review, T-lang, T-edition

#2359 use repo name in push pr title
  josh-sync/src/sync.rs
Labels: S-waiting-on-review, WG-rustc-dev-guide

#2352 Enable [behind-upstream] triagebot option
  triagebot.toml
Labels: S-waiting-on-review, A-CI, WG-rustc-dev-guide
