Repository rust-lang/rustc-dev-guide, pull requests merged in 2025-03, with the labels that each got.

#2258 Rewrite effects checking chapter
  src/SUMMARY.md
  src/effects.md
Labels: S-waiting-on-review, T-types

#2293 Rustc pull
  rust-version
  src/backend/debugging.md
  src/backend/updating-llvm.md
  src/building/compiler-documenting.md
  src/building/how-to-build-and-run.md
  src/building/new-target.md
  src/building/optimized-build.md
  src/building/suggested.md
  src/compiler-debugging.md
  src/fuzzing.md
  src/llvm-coverage-instrumentation.md
  src/overview.md
  src/profile-guided-optimization.md
  src/profiling.md
  src/profiling/with_perf.md
  src/profiling/with_rustc_perf.md
  src/profiling/wpa_profiling.md
  src/rustdoc.md
  src/sanitizers.md
  src/tests/ci.md
  src/tests/compiletest.md
  src/tests/directives.md
  src/tests/docker.md
  src/tests/running.md
  src/tracing.md
Labels: S-waiting-on-review, WG-rustc-dev-guide

#2268 Add issue link for explaining that why rustc_private linker fails
  src/SUMMARY.md
  src/rustc-driver/remarks-on-perma-unstable-features.md
Labels: S-waiting-on-author, T-compiler

#2296 Don't linkcheck external web links in PR CI
  .github/workflows/ci.yml
Labels: S-waiting-on-review, A-linkcheck, WG-rustc-dev-guide

#2295 add new section on the `rustdoc` test suite
  src/SUMMARY.md
  src/rustdoc-internals/rustdoc-test-suite.md
  src/rustdoc.md
Labels: S-waiting-on-review, T-rustdoc

#2265 Update `ParamEnv` section for `TypingEnv` changes
  src/SUMMARY.md
  src/appendix/code-index.md
  src/const-eval.md
  src/param_env/param_env_acquisition.md
  src/param_env/param_env_construction_internals.md
  src/param_env/param_env_summary.md
  src/param_env/param_env_what_is_it.md
  src/traits/caching.md
  src/traits/resolution.md
  src/typing_parameter_envs.md
Labels: S-waiting-on-author, T-types

#2299 Slightly reorganize ecosystem tests, stub out codegen backend test pages
  book.toml
  src/SUMMARY.md
  src/notification-groups/fuchsia.md
  src/tests/codegen-backend-tests/cg_clif.md
  src/tests/codegen-backend-tests/cg_gcc.md
  src/tests/codegen-backend-tests/intro.md
  src/tests/ecosystem-test-jobs/fuchsia.md
  src/tests/ecosystem-test-jobs/rust-for-linux.md
  src/tests/ecosystem.md
  src/tests/intro.md
Labels: S-waiting-on-review, WG-rustc-dev-guide

#2288 mention that known-bug test directive takes arguments
  src/tests/ui.md
Labels: S-waiting-on-author, T-bootstrap
