Repository rust-lang/rustc-dev-guide, pull requests merged in 2025-01, with the labels that each got.

#2183 Add tooling for performing Josh synces
  README.md
  josh-sync/Cargo.lock
  josh-sync/Cargo.toml
  josh-sync/README.md
  josh-sync/src/main.rs
  josh-sync/src/sync.rs
  rust-version
Labels: S-waiting-on-review, WG-rustc-dev-guide, A-josh

#2182 Document josh subtrees and update subtree repository list
  src/external-repos.md
Labels: S-waiting-on-review, A-josh

#2192 Split stuff out of representing types, and rewrite early/late bound chapter
  src/SUMMARY.md
  src/early-late-bound-params/early-late-bound-implementation-nuances.md
  src/early-late-bound-params/turbofishing-and-early-late-bound.md
  src/early_late_parameters.md
  src/generic_parameters_summary.md
  src/ty_module/early_binder.md
Labels: S-waiting-on-review, T-types

#2197 Add rustc-dev-guide to the list of repositories managed by josh
  src/external-repos.md
Labels: A-josh

#2194 Only keep issue triage docs in Forge docs
  src/contributing.md
Labels: S-waiting-on-review, T-compiler, T-release, WG-triage

#2030 Save linkcheck cache always
  .github/workflows/ci.yml
  book.toml
Labels: S-waiting-on-review, C-CI, A-linkcheck, WG-rustc-dev-guide

#2205 Document how to find the configuration used in CI
  src/tests/ci.md
Labels: S-waiting-on-review, T-infra, A-CI

#2202 Add a CI workflow for performing rustc-pull automatically
  .github/workflows/rustc-pull.yml
  josh-sync/src/sync.rs
  triagebot.toml
Labels: S-waiting-on-review, A-CI, WG-rustc-dev-guide

#2212 compiletest: fix outdated `rustdoc-js` test suite name
  src/tests/directives.md
Labels: A-compiletest, T-bootstrap

#2211 remove outdated text about wfx implies
  src/solve/invariants.md
Labels: S-waiting-on-review, T-types

#2213 Document how to install a suitable `josh-proxy` locally
  README.md
Labels: S-waiting-on-review, WG-rustc-dev-guide, A-josh

#2229 Add some extra pointers for rustdoc frontend devs
  src/rustdoc.md
Labels: T-rustdoc
