Repository rust-lang/rustc-dev-guide, pull requests merged in 2025-05, with the labels that each got.

#2323 Align advice to discourage issue-number-only names
  src/tests/best-practices.md
Labels: S-waiting-on-author, A-test-suite, T-compiler

#2403 ~? annotation type is special
  src/tests/ui.md
Labels: S-waiting-on-author, A-compiletest, A-test-suite, T-compiler

#2404 rustdoc.md: reorder list so test suites are not split up
  src/rustdoc.md
Labels: S-waiting-on-review, C-cleanup, T-rustdoc

#2405 Remove mentions of rust-lang-ci/rust
  src/tests/ci.md
Labels: T-infra, A-CI

#2425 Adjust triagebot config
  triagebot.toml
Labels: A-meta, WG-rustc-dev-guide

#2431 Setup basic `r? rustc-dev-guide` review group
  triagebot.toml
Labels: S-waiting-on-review

#2433 replace a broken sentence
  src/building/suggested.md
Labels: S-waiting-on-review

#2434 update surname (was lekhonkhobe previously) and email
  .mailmap
Labels: S-waiting-on-review
